import paramiko
c = paramiko.SSHClient()
c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
c.connect('connect.bjb1.seetacloud.com', port=50472, username='root', password='i9D1S9IoRMLR', timeout=10)
def run(cmd):
    _, o, _ = c.exec_command(cmd, timeout=15)
    return o.read().decode(errors='replace').strip()

print('=== extreme_test.log (D+A+B) ===')
print(run('tail -15 /root/extreme_test.log 2>&1'))
print()
print('=== 进程 ===')
print(run('ps aux | grep python | grep -v grep'))
print()
print('=== GPU ===')
print(run('nvidia-smi --query-gpu=utilization.gpu,memory.used --format=csv,noheader'))
print()
print('=== C 日志 ===')
print(run('tail -5 /root/run_c_1000m.log 2>&1 || echo NONE'))
c.close()
